version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
    - ./data:/var/lib/mysql
    - ./scripts:/scripts
    - ./dataset:/dataset
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    working_dir: /scripts
