CREATE DATABASE tf_icaro_sara_dw;
USE tf_icaro_sara_dw;

CREATE TABLE TEMPO (
    idTempo INTEGER NOT NULL AUTO_INCREMENT,
    data DATE NOT NULL,

    CONSTRAINT TEMPO_PK PRIMARY KEY (idTempo)
) Engine=InnoDB;

CREATE TABLE LOCAL (
    idLocal INTEGER NOT NULL AUTO_INCREMENT,
    latitude FLOAT,
    longitude FLOAT,
    logradouro VARCHAR(50) NOT NULL,
    cidade VARCHAR(50) NOT NULL,
    numero INT NOT NULL,

    CONSTRAINT LOCAL_PK PRIMARY KEY (idLocal)
) Engine=InnoDB;

CREATE TABLE BOLETIM (
    idBoletim INTEGER NOT NULL AUTO_INCREMENT,
    numBO INTEGER NOT NULL,
    anoBO INT NOT NULL,
    rubrica VARCHAR(50),

    CONSTRAINT BOLETIM_PK PRIMARY KEY (idBoletim)
) Engine=InnoDB;

CREATE TABLE DELEGACIA (
    idDelegacia INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(70) NOT NULL,
    departamento VARCHAR(70) NOT NULL,
    cidade VARCHAR(50),

    CONSTRAINT DELEGACIA_PK PRIMARY KEY (idDelegacia)
) Engine=InnoDB;

CREATE TABLE STATUS (
    idStatus INTEGER NOT NULL AUTO_INCREMENT,
    status ENUM('C','T') NOT NULL,
    conduta VARCHAR(50),
    desdobramento VARCHAR(500),

    CONSTRAINT STATUS_PK PRIMARY KEY (idStatus)
) Engine=InnoDB;

CREATE TABLE OCORRENCIA (
    idBoletim INTEGER NOT NULL,
    idTempo INTEGER NOT NULL,
    idDelegacia INTEGER NOT NULL,
    idLocal INTEGER NOT NULL,
    idStatus INTEGER NOT NULL,
    qtdBOs INT NOT NULL,
    qtdDesdobramentosDiferentes INT NOT NULL,

    CONSTRAINT OCORRENCIA_BOLETIM_FK FOREIGN KEY (idBoletim) 
        REFERENCES BOLETIM(idBoletim)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT,

    CONSTRAINT OCORRENCIA_TEMPO_FK FOREIGN KEY (idTempo) 
        REFERENCES TEMPO(idTempo)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT,

    CONSTRAINT OCORRENCIA_DELEGACIA_FK FOREIGN KEY (idDelegacia) 
        REFERENCES TEMPO(idTempo)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT,

    CONSTRAINT OCORRENCIA_LOCAL_FK FOREIGN KEY (idLocal) 
        REFERENCES LOCAL(idLocal)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT,

    CONSTRAINT OCORRENCIA_STATUS_FK FOREIGN KEY (idStatus) 
        REFERENCES STATUS(idStatus)
            ON DELETE RESTRICT
            ON UPDATE RESTRICT
) Engine=InnoDB;


-- FK Indexes for fact table
CREATE INDEX OCORRENCIA_TEMPO_IDX ON OCORRENCIA(idTempo);
CREATE INDEX OCORRENCIA_LOCAL_IDX ON OCORRENCIA(idLocal);
CREATE INDEX OCORRENCIA_BOLETIM_IDX ON OCORRENCIA(idBoletim);
CREATE INDEX OCORRENCIA_DELEGACIA_IDX ON OCORRENCIA(idDelegacia);
CREATE INDEX OCORRENCIA_STATUS_IDX ON OCORRENCIA(idStatus);
